### YamlMime:ManagedReference
items:
- uid: Beutl.Configuration.LibraryTabDisplayMode
  commentId: T:Beutl.Configuration.LibraryTabDisplayMode
  id: LibraryTabDisplayMode
  parent: Beutl.Configuration
  children:
  - Beutl.Configuration.LibraryTabDisplayMode.Hide
  - Beutl.Configuration.LibraryTabDisplayMode.Show
  langs:
  - csharp
  - vb
  name: LibraryTabDisplayMode
  nameWithType: LibraryTabDisplayMode
  fullName: Beutl.Configuration.LibraryTabDisplayMode
  type: Enum
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: public enum LibraryTabDisplayMode
    content.vb: Public Enum LibraryTabDisplayMode
- uid: Beutl.Configuration.LibraryTabDisplayMode.Show
  commentId: F:Beutl.Configuration.LibraryTabDisplayMode.Show
  id: Show
  parent: Beutl.Configuration.LibraryTabDisplayMode
  langs:
  - csharp
  - vb
  name: Show
  nameWithType: LibraryTabDisplayMode.Show
  fullName: Beutl.Configuration.LibraryTabDisplayMode.Show
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Show = 0
    return:
      type: Beutl.Configuration.LibraryTabDisplayMode
- uid: Beutl.Configuration.LibraryTabDisplayMode.Hide
  commentId: F:Beutl.Configuration.LibraryTabDisplayMode.Hide
  id: Hide
  parent: Beutl.Configuration.LibraryTabDisplayMode
  langs:
  - csharp
  - vb
  name: Hide
  nameWithType: LibraryTabDisplayMode.Hide
  fullName: Beutl.Configuration.LibraryTabDisplayMode.Hide
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Hide = 1
    return:
      type: Beutl.Configuration.LibraryTabDisplayMode
references:
- uid: Beutl.Configuration
  commentId: N:Beutl.Configuration
  isExternal: true
  href: Beutl.html
  name: Beutl.Configuration
  nameWithType: Beutl.Configuration
  fullName: Beutl.Configuration
  spec.csharp:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
  spec.vb:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
- uid: Beutl.Configuration.LibraryTabDisplayMode
  commentId: T:Beutl.Configuration.LibraryTabDisplayMode
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.LibraryTabDisplayMode.html
  name: LibraryTabDisplayMode
  nameWithType: LibraryTabDisplayMode
  fullName: Beutl.Configuration.LibraryTabDisplayMode
