### YamlMime:ManagedReference
items:
- uid: Beutl.Configuration.FrameCacheConfigColorType
  commentId: T:Beutl.Configuration.FrameCacheConfigColorType
  id: FrameCacheConfigColorType
  parent: Beutl.Configuration
  children:
  - Beutl.Configuration.FrameCacheConfigColorType.RGBA
  - Beutl.Configuration.FrameCacheConfigColorType.YUV
  langs:
  - csharp
  - vb
  name: FrameCacheConfigColorType
  nameWithType: FrameCacheConfigColorType
  fullName: Beutl.Configuration.FrameCacheConfigColorType
  type: Enum
  source:
    href: https://github.com/b-editor/beutl/blob/main/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: public enum FrameCacheConfigColorType
    content.vb: Public Enum FrameCacheConfigColorType
- uid: Beutl.Configuration.FrameCacheConfigColorType.RGBA
  commentId: F:Beutl.Configuration.FrameCacheConfigColorType.RGBA
  id: RGBA
  parent: Beutl.Configuration.FrameCacheConfigColorType
  langs:
  - csharp
  - vb
  name: RGBA
  nameWithType: FrameCacheConfigColorType.RGBA
  fullName: Beutl.Configuration.FrameCacheConfigColorType.RGBA
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/main/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: RGBA = 0
    return:
      type: Beutl.Configuration.FrameCacheConfigColorType
- uid: Beutl.Configuration.FrameCacheConfigColorType.YUV
  commentId: F:Beutl.Configuration.FrameCacheConfigColorType.YUV
  id: YUV
  parent: Beutl.Configuration.FrameCacheConfigColorType
  langs:
  - csharp
  - vb
  name: YUV
  nameWithType: FrameCacheConfigColorType.YUV
  fullName: Beutl.Configuration.FrameCacheConfigColorType.YUV
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/main/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: YUV = 1
    return:
      type: Beutl.Configuration.FrameCacheConfigColorType
references:
- uid: Beutl.Configuration
  commentId: N:Beutl.Configuration
  isExternal: true
  href: Beutl.html
  name: Beutl.Configuration
  nameWithType: Beutl.Configuration
  fullName: Beutl.Configuration
  spec.csharp:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
  spec.vb:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
- uid: Beutl.Configuration.FrameCacheConfigColorType
  commentId: T:Beutl.Configuration.FrameCacheConfigColorType
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.FrameCacheConfigColorType.html
  name: FrameCacheConfigColorType
  nameWithType: FrameCacheConfigColorType
  fullName: Beutl.Configuration.FrameCacheConfigColorType
