### YamlMime:ManagedReference
items:
- uid: Beutl.BeutlEnvironment
  commentId: T:Beutl.BeutlEnvironment
  id: BeutlEnvironment
  parent: Beutl
  children:
  - Beutl.BeutlEnvironment.GetHomeDirectoryPath
  - Beutl.BeutlEnvironment.GetPackagesDirectoryPath
  - Beutl.BeutlEnvironment.GetSideloadsDirectoryPath
  - Beutl.BeutlEnvironment.HomeVariable
  langs:
  - csharp
  - vb
  name: BeutlEnvironment
  nameWithType: BeutlEnvironment
  fullName: Beutl.BeutlEnvironment
  type: Class
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Core/BeutlEnvironment.cs
  assemblies:
  - Beutl.Core
  namespace: Beutl
  syntax:
    content: public static class BeutlEnvironment
    content.vb: Public Module BeutlEnvironment
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Beutl.BeutlEnvironment.HomeVariable
  commentId: F:Beutl.BeutlEnvironment.HomeVariable
  id: HomeVariable
  parent: Beutl.BeutlEnvironment
  langs:
  - csharp
  - vb
  name: HomeVariable
  nameWithType: BeutlEnvironment.HomeVariable
  fullName: Beutl.BeutlEnvironment.HomeVariable
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Core/BeutlEnvironment.cs
  assemblies:
  - Beutl.Core
  namespace: Beutl
  syntax:
    content: public const string HomeVariable = "BEUTL_HOME"
    return:
      type: System.String
    content.vb: Public Const HomeVariable As String = "BEUTL_HOME"
- uid: Beutl.BeutlEnvironment.GetHomeDirectoryPath
  commentId: M:Beutl.BeutlEnvironment.GetHomeDirectoryPath
  id: GetHomeDirectoryPath
  parent: Beutl.BeutlEnvironment
  langs:
  - csharp
  - vb
  name: GetHomeDirectoryPath()
  nameWithType: BeutlEnvironment.GetHomeDirectoryPath()
  fullName: Beutl.BeutlEnvironment.GetHomeDirectoryPath()
  type: Method
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Core/BeutlEnvironment.cs
  assemblies:
  - Beutl.Core
  namespace: Beutl
  syntax:
    content: public static string GetHomeDirectoryPath()
    return:
      type: System.String
    content.vb: Public Shared Function GetHomeDirectoryPath() As String
  overload: Beutl.BeutlEnvironment.GetHomeDirectoryPath*
- uid: Beutl.BeutlEnvironment.GetPackagesDirectoryPath
  commentId: M:Beutl.BeutlEnvironment.GetPackagesDirectoryPath
  id: GetPackagesDirectoryPath
  parent: Beutl.BeutlEnvironment
  langs:
  - csharp
  - vb
  name: GetPackagesDirectoryPath()
  nameWithType: BeutlEnvironment.GetPackagesDirectoryPath()
  fullName: Beutl.BeutlEnvironment.GetPackagesDirectoryPath()
  type: Method
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Core/BeutlEnvironment.cs
  assemblies:
  - Beutl.Core
  namespace: Beutl
  syntax:
    content: public static string GetPackagesDirectoryPath()
    return:
      type: System.String
    content.vb: Public Shared Function GetPackagesDirectoryPath() As String
  overload: Beutl.BeutlEnvironment.GetPackagesDirectoryPath*
- uid: Beutl.BeutlEnvironment.GetSideloadsDirectoryPath
  commentId: M:Beutl.BeutlEnvironment.GetSideloadsDirectoryPath
  id: GetSideloadsDirectoryPath
  parent: Beutl.BeutlEnvironment
  langs:
  - csharp
  - vb
  name: GetSideloadsDirectoryPath()
  nameWithType: BeutlEnvironment.GetSideloadsDirectoryPath()
  fullName: Beutl.BeutlEnvironment.GetSideloadsDirectoryPath()
  type: Method
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Core/BeutlEnvironment.cs
  assemblies:
  - Beutl.Core
  namespace: Beutl
  syntax:
    content: public static string GetSideloadsDirectoryPath()
    return:
      type: System.String
    content.vb: Public Shared Function GetSideloadsDirectoryPath() As String
  overload: Beutl.BeutlEnvironment.GetSideloadsDirectoryPath*
references:
- uid: Beutl
  commentId: N:Beutl
  isExternal: true
  href: Beutl.html
  name: Beutl
  nameWithType: Beutl
  fullName: Beutl
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Beutl.BeutlEnvironment.GetHomeDirectoryPath*
  commentId: Overload:Beutl.BeutlEnvironment.GetHomeDirectoryPath
  isExternal: true
  href: Beutl.BeutlEnvironment.html#Beutl_BeutlEnvironment_GetHomeDirectoryPath
  name: GetHomeDirectoryPath
  nameWithType: BeutlEnvironment.GetHomeDirectoryPath
  fullName: Beutl.BeutlEnvironment.GetHomeDirectoryPath
- uid: Beutl.BeutlEnvironment.GetPackagesDirectoryPath*
  commentId: Overload:Beutl.BeutlEnvironment.GetPackagesDirectoryPath
  isExternal: true
  href: Beutl.BeutlEnvironment.html#Beutl_BeutlEnvironment_GetPackagesDirectoryPath
  name: GetPackagesDirectoryPath
  nameWithType: BeutlEnvironment.GetPackagesDirectoryPath
  fullName: Beutl.BeutlEnvironment.GetPackagesDirectoryPath
- uid: Beutl.BeutlEnvironment.GetSideloadsDirectoryPath*
  commentId: Overload:Beutl.BeutlEnvironment.GetSideloadsDirectoryPath
  isExternal: true
  href: Beutl.BeutlEnvironment.html#Beutl_BeutlEnvironment_GetSideloadsDirectoryPath
  name: GetSideloadsDirectoryPath
  nameWithType: BeutlEnvironment.GetSideloadsDirectoryPath
  fullName: Beutl.BeutlEnvironment.GetSideloadsDirectoryPath
