### YamlMime:ManagedReference
items:
- uid: Beutl.Configuration.ViewConfig.ViewTheme
  commentId: T:Beutl.Configuration.ViewConfig.ViewTheme
  id: ViewConfig.ViewTheme
  parent: Beutl.Configuration
  children:
  - Beutl.Configuration.ViewConfig.ViewTheme.Dark
  - Beutl.Configuration.ViewConfig.ViewTheme.HighContrast
  - Beutl.Configuration.ViewConfig.ViewTheme.Light
  - Beutl.Configuration.ViewConfig.ViewTheme.System
  langs:
  - csharp
  - vb
  name: ViewConfig.ViewTheme
  nameWithType: ViewConfig.ViewTheme
  fullName: Beutl.Configuration.ViewConfig.ViewTheme
  type: Enum
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/ViewConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: public enum ViewConfig.ViewTheme
    content.vb: Public Enum ViewConfig.ViewTheme
- uid: Beutl.Configuration.ViewConfig.ViewTheme.Light
  commentId: F:Beutl.Configuration.ViewConfig.ViewTheme.Light
  id: Light
  parent: Beutl.Configuration.ViewConfig.ViewTheme
  langs:
  - csharp
  - vb
  name: Light
  nameWithType: ViewConfig.ViewTheme.Light
  fullName: Beutl.Configuration.ViewConfig.ViewTheme.Light
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/ViewConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Light = 0
    return:
      type: Beutl.Configuration.ViewConfig.ViewTheme
- uid: Beutl.Configuration.ViewConfig.ViewTheme.Dark
  commentId: F:Beutl.Configuration.ViewConfig.ViewTheme.Dark
  id: Dark
  parent: Beutl.Configuration.ViewConfig.ViewTheme
  langs:
  - csharp
  - vb
  name: Dark
  nameWithType: ViewConfig.ViewTheme.Dark
  fullName: Beutl.Configuration.ViewConfig.ViewTheme.Dark
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/ViewConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Dark = 1
    return:
      type: Beutl.Configuration.ViewConfig.ViewTheme
- uid: Beutl.Configuration.ViewConfig.ViewTheme.HighContrast
  commentId: F:Beutl.Configuration.ViewConfig.ViewTheme.HighContrast
  id: HighContrast
  parent: Beutl.Configuration.ViewConfig.ViewTheme
  langs:
  - csharp
  - vb
  name: HighContrast
  nameWithType: ViewConfig.ViewTheme.HighContrast
  fullName: Beutl.Configuration.ViewConfig.ViewTheme.HighContrast
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/ViewConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: HighContrast = 2
    return:
      type: Beutl.Configuration.ViewConfig.ViewTheme
- uid: Beutl.Configuration.ViewConfig.ViewTheme.System
  commentId: F:Beutl.Configuration.ViewConfig.ViewTheme.System
  id: System
  parent: Beutl.Configuration.ViewConfig.ViewTheme
  langs:
  - csharp
  - vb
  name: System
  nameWithType: ViewConfig.ViewTheme.System
  fullName: Beutl.Configuration.ViewConfig.ViewTheme.System
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/ViewConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: System = 3
    return:
      type: Beutl.Configuration.ViewConfig.ViewTheme
references:
- uid: Beutl.Configuration
  commentId: N:Beutl.Configuration
  isExternal: true
  href: Beutl.html
  name: Beutl.Configuration
  nameWithType: Beutl.Configuration
  fullName: Beutl.Configuration
  spec.csharp:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
  spec.vb:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
- uid: Beutl.Configuration.ViewConfig.ViewTheme
  commentId: T:Beutl.Configuration.ViewConfig.ViewTheme
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.ViewConfig.html
  name: ViewConfig.ViewTheme
  nameWithType: ViewConfig.ViewTheme
  fullName: Beutl.Configuration.ViewConfig.ViewTheme
  spec.csharp:
  - uid: Beutl.Configuration.ViewConfig
    name: ViewConfig
    isExternal: true
    href: Beutl.Configuration.ViewConfig.html
  - name: .
  - uid: Beutl.Configuration.ViewConfig.ViewTheme
    name: ViewTheme
    isExternal: true
    href: Beutl.Configuration.ViewConfig.ViewTheme.html
  spec.vb:
  - uid: Beutl.Configuration.ViewConfig
    name: ViewConfig
    isExternal: true
    href: Beutl.Configuration.ViewConfig.html
  - name: .
  - uid: Beutl.Configuration.ViewConfig.ViewTheme
    name: ViewTheme
    isExternal: true
    href: Beutl.Configuration.ViewConfig.ViewTheme.html
