### YamlMime:ManagedReference
items:
- uid: Beutl.Configuration.FrameCacheConfigScale
  commentId: T:Beutl.Configuration.FrameCacheConfigScale
  id: FrameCacheConfigScale
  parent: Beutl.Configuration
  children:
  - Beutl.Configuration.FrameCacheConfigScale.FitToPreviewer
  - Beutl.Configuration.FrameCacheConfigScale.Half
  - Beutl.Configuration.FrameCacheConfigScale.Original
  - Beutl.Configuration.FrameCacheConfigScale.Quarter
  langs:
  - csharp
  - vb
  name: FrameCacheConfigScale
  nameWithType: FrameCacheConfigScale
  fullName: Beutl.Configuration.FrameCacheConfigScale
  type: Enum
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: public enum FrameCacheConfigScale
    content.vb: Public Enum FrameCacheConfigScale
- uid: Beutl.Configuration.FrameCacheConfigScale.Original
  commentId: F:Beutl.Configuration.FrameCacheConfigScale.Original
  id: Original
  parent: Beutl.Configuration.FrameCacheConfigScale
  langs:
  - csharp
  - vb
  name: Original
  nameWithType: FrameCacheConfigScale.Original
  fullName: Beutl.Configuration.FrameCacheConfigScale.Original
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Original = 0
    return:
      type: Beutl.Configuration.FrameCacheConfigScale
- uid: Beutl.Configuration.FrameCacheConfigScale.FitToPreviewer
  commentId: F:Beutl.Configuration.FrameCacheConfigScale.FitToPreviewer
  id: FitToPreviewer
  parent: Beutl.Configuration.FrameCacheConfigScale
  langs:
  - csharp
  - vb
  name: FitToPreviewer
  nameWithType: FrameCacheConfigScale.FitToPreviewer
  fullName: Beutl.Configuration.FrameCacheConfigScale.FitToPreviewer
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: FitToPreviewer = 1
    return:
      type: Beutl.Configuration.FrameCacheConfigScale
- uid: Beutl.Configuration.FrameCacheConfigScale.Half
  commentId: F:Beutl.Configuration.FrameCacheConfigScale.Half
  id: Half
  parent: Beutl.Configuration.FrameCacheConfigScale
  langs:
  - csharp
  - vb
  name: Half
  nameWithType: FrameCacheConfigScale.Half
  fullName: Beutl.Configuration.FrameCacheConfigScale.Half
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Half = 2
    return:
      type: Beutl.Configuration.FrameCacheConfigScale
- uid: Beutl.Configuration.FrameCacheConfigScale.Quarter
  commentId: F:Beutl.Configuration.FrameCacheConfigScale.Quarter
  id: Quarter
  parent: Beutl.Configuration.FrameCacheConfigScale
  langs:
  - csharp
  - vb
  name: Quarter
  nameWithType: FrameCacheConfigScale.Quarter
  fullName: Beutl.Configuration.FrameCacheConfigScale.Quarter
  type: Field
  source:
    href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/EditorConfig.cs
  assemblies:
  - Beutl.Configuration
  namespace: Beutl.Configuration
  syntax:
    content: Quarter = 3
    return:
      type: Beutl.Configuration.FrameCacheConfigScale
references:
- uid: Beutl.Configuration
  commentId: N:Beutl.Configuration
  isExternal: true
  href: Beutl.html
  name: Beutl.Configuration
  nameWithType: Beutl.Configuration
  fullName: Beutl.Configuration
  spec.csharp:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
  spec.vb:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
- uid: Beutl.Configuration.FrameCacheConfigScale
  commentId: T:Beutl.Configuration.FrameCacheConfigScale
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.FrameCacheConfigScale.html
  name: FrameCacheConfigScale
  nameWithType: FrameCacheConfigScale
  fullName: Beutl.Configuration.FrameCacheConfigScale
