### YamlMime:ManagedReference
items:
- uid: Beutl.Configuration
  commentId: N:Beutl.Configuration
  id: Beutl.Configuration
  children:
  - Beutl.Configuration.BackupConfig
  - Beutl.Configuration.ConfigurationBase
  - Beutl.Configuration.DefaultPreferences
  - Beutl.Configuration.EditorConfig
  - Beutl.Configuration.ExtensionConfig
  - Beutl.Configuration.ExtensionConfig.TypeLazy
  - Beutl.Configuration.FontConfig
  - Beutl.Configuration.FrameCacheConfigColorType
  - Beutl.Configuration.FrameCacheConfigScale
  - Beutl.Configuration.GlobalConfiguration
  - Beutl.Configuration.GraphicsConfig
  - Beutl.Configuration.IPreferences
  - Beutl.Configuration.LibraryTabDisplayMode
  - Beutl.Configuration.Preferences
  - Beutl.Configuration.TelemetryConfig
  - Beutl.Configuration.ViewConfig
  - Beutl.Configuration.ViewConfig.ViewTheme
  langs:
  - csharp
  - vb
  name: Beutl.Configuration
  nameWithType: Beutl.Configuration
  fullName: Beutl.Configuration
  type: Namespace
  assemblies:
  - Beutl.Configuration
references:
- uid: Beutl.Configuration.BackupConfig
  commentId: T:Beutl.Configuration.BackupConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.BackupConfig.html
  name: BackupConfig
  nameWithType: BackupConfig
  fullName: Beutl.Configuration.BackupConfig
- uid: Beutl.Configuration.ConfigurationBase
  commentId: T:Beutl.Configuration.ConfigurationBase
  parent: Beutl.Configuration
  isExternal: true
  href: https://github.com/b-editor/beutl/blob/c51d1f13e20b455e75ababfd9893c5cc593443c4/src/Beutl.Configuration/ConfigurationBase.cs
  name: ConfigurationBase
  nameWithType: ConfigurationBase
  fullName: Beutl.Configuration.ConfigurationBase
- uid: Beutl.Configuration.DefaultPreferences
  commentId: T:Beutl.Configuration.DefaultPreferences
  isExternal: true
  href: Beutl.Configuration.DefaultPreferences.html
  name: DefaultPreferences
  nameWithType: DefaultPreferences
  fullName: Beutl.Configuration.DefaultPreferences
- uid: Beutl.Configuration.LibraryTabDisplayMode
  commentId: T:Beutl.Configuration.LibraryTabDisplayMode
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.LibraryTabDisplayMode.html
  name: LibraryTabDisplayMode
  nameWithType: LibraryTabDisplayMode
  fullName: Beutl.Configuration.LibraryTabDisplayMode
- uid: Beutl.Configuration.FrameCacheConfigScale
  commentId: T:Beutl.Configuration.FrameCacheConfigScale
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.FrameCacheConfigScale.html
  name: FrameCacheConfigScale
  nameWithType: FrameCacheConfigScale
  fullName: Beutl.Configuration.FrameCacheConfigScale
- uid: Beutl.Configuration.FrameCacheConfigColorType
  commentId: T:Beutl.Configuration.FrameCacheConfigColorType
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.FrameCacheConfigColorType.html
  name: FrameCacheConfigColorType
  nameWithType: FrameCacheConfigColorType
  fullName: Beutl.Configuration.FrameCacheConfigColorType
- uid: Beutl.Configuration.EditorConfig
  commentId: T:Beutl.Configuration.EditorConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.EditorConfig.html
  name: EditorConfig
  nameWithType: EditorConfig
  fullName: Beutl.Configuration.EditorConfig
- uid: Beutl.Configuration.ExtensionConfig
  commentId: T:Beutl.Configuration.ExtensionConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.ExtensionConfig.html
  name: ExtensionConfig
  nameWithType: ExtensionConfig
  fullName: Beutl.Configuration.ExtensionConfig
- uid: Beutl.Configuration.ExtensionConfig.TypeLazy
  commentId: T:Beutl.Configuration.ExtensionConfig.TypeLazy
  isExternal: true
  href: Beutl.Configuration.ExtensionConfig.html
  name: ExtensionConfig.TypeLazy
  nameWithType: ExtensionConfig.TypeLazy
  fullName: Beutl.Configuration.ExtensionConfig.TypeLazy
  spec.csharp:
  - uid: Beutl.Configuration.ExtensionConfig
    name: ExtensionConfig
    isExternal: true
    href: Beutl.Configuration.ExtensionConfig.html
  - name: .
  - uid: Beutl.Configuration.ExtensionConfig.TypeLazy
    name: TypeLazy
    isExternal: true
    href: Beutl.Configuration.ExtensionConfig.TypeLazy.html
  spec.vb:
  - uid: Beutl.Configuration.ExtensionConfig
    name: ExtensionConfig
    isExternal: true
    href: Beutl.Configuration.ExtensionConfig.html
  - name: .
  - uid: Beutl.Configuration.ExtensionConfig.TypeLazy
    name: TypeLazy
    isExternal: true
    href: Beutl.Configuration.ExtensionConfig.TypeLazy.html
- uid: Beutl.Configuration.FontConfig
  commentId: T:Beutl.Configuration.FontConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.FontConfig.html
  name: FontConfig
  nameWithType: FontConfig
  fullName: Beutl.Configuration.FontConfig
- uid: Beutl.Configuration.GlobalConfiguration
  commentId: T:Beutl.Configuration.GlobalConfiguration
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.GlobalConfiguration.html
  name: GlobalConfiguration
  nameWithType: GlobalConfiguration
  fullName: Beutl.Configuration.GlobalConfiguration
- uid: Beutl.Configuration.GraphicsConfig
  commentId: T:Beutl.Configuration.GraphicsConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.GraphicsConfig.html
  name: GraphicsConfig
  nameWithType: GraphicsConfig
  fullName: Beutl.Configuration.GraphicsConfig
- uid: Beutl.Configuration.IPreferences
  commentId: T:Beutl.Configuration.IPreferences
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.IPreferences.html
  name: IPreferences
  nameWithType: IPreferences
  fullName: Beutl.Configuration.IPreferences
- uid: Beutl.Configuration.Preferences
  commentId: T:Beutl.Configuration.Preferences
  isExternal: true
  href: Beutl.Configuration.Preferences.html
  name: Preferences
  nameWithType: Preferences
  fullName: Beutl.Configuration.Preferences
- uid: Beutl.Configuration.TelemetryConfig
  commentId: T:Beutl.Configuration.TelemetryConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.TelemetryConfig.html
  name: TelemetryConfig
  nameWithType: TelemetryConfig
  fullName: Beutl.Configuration.TelemetryConfig
- uid: Beutl.Configuration.ViewConfig
  commentId: T:Beutl.Configuration.ViewConfig
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.ViewConfig.html
  name: ViewConfig
  nameWithType: ViewConfig
  fullName: Beutl.Configuration.ViewConfig
- uid: Beutl.Configuration.ViewConfig.ViewTheme
  commentId: T:Beutl.Configuration.ViewConfig.ViewTheme
  parent: Beutl.Configuration
  isExternal: true
  href: Beutl.Configuration.ViewConfig.html
  name: ViewConfig.ViewTheme
  nameWithType: ViewConfig.ViewTheme
  fullName: Beutl.Configuration.ViewConfig.ViewTheme
  spec.csharp:
  - uid: Beutl.Configuration.ViewConfig
    name: ViewConfig
    isExternal: true
    href: Beutl.Configuration.ViewConfig.html
  - name: .
  - uid: Beutl.Configuration.ViewConfig.ViewTheme
    name: ViewTheme
    isExternal: true
    href: Beutl.Configuration.ViewConfig.ViewTheme.html
  spec.vb:
  - uid: Beutl.Configuration.ViewConfig
    name: ViewConfig
    isExternal: true
    href: Beutl.Configuration.ViewConfig.html
  - name: .
  - uid: Beutl.Configuration.ViewConfig.ViewTheme
    name: ViewTheme
    isExternal: true
    href: Beutl.Configuration.ViewConfig.ViewTheme.html
- uid: Beutl.Configuration
  commentId: N:Beutl.Configuration
  isExternal: true
  href: Beutl.html
  name: Beutl.Configuration
  nameWithType: Beutl.Configuration
  fullName: Beutl.Configuration
  spec.csharp:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
  spec.vb:
  - uid: Beutl
    name: Beutl
    isExternal: true
    href: Beutl.html
  - name: .
  - uid: Beutl.Configuration
    name: Configuration
    isExternal: true
    href: Beutl.Configuration.html
